version: 2
updates:
  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      compatible-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /web
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      compatible-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    groups:
      compatible-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
